### ISSUE TITLE
Syntax sugar proposal

### ISSUE THREAD

**Issue by joao-alberto** [entria/responsiveness#2]
What do you think about a smaller way to define the sizes?

Something like:
``` js
<Grid.Col sizes={12, 6, 3}>1</Grid.Col>
```
Where the parameters is from smaller to greater breakpoints (small, medium, large).
Of course, this will be a `alias` for the current way to define sizes and not a replacement.

**Comment by felippepuhle** [comment]
It sounds good. Would you send a PR with this?

**Comment by joao-alberto** [comment]
@felippepuhle Yep! :metal:
